backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "vision"
    label: "Vision"
    folder: "src/visions"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Image", name: "featuredimage", widget: image, hint: 'Find gifs with: https://codepen.io/barefootfunk/pen/mdPxgaG'}
      - {label: "Description", name: "body", widget: "markdown", pattern: ['^.{1,280}$', "Must have 1-280 characters"]}
      - {label: "Heart Choice", name: "heartChoice", widget: "string", required: false}
      - {label: "Mind Choice", name: "mindChoice", widget: "string", required: false}
      - {label: "Chaos Choice", name: "chaosChoice", widget: "string", required: false}